### ISSUE TITLE
illegal memory access

### ISSUE THREAD

**Issue by greaber** [JianGoForIt/YellowFin_Pytorch#16]
Feel free to close since it seems like a PyTorch bug, but as a heads up, in case others hit the same issue, on some runs I got this:

```
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    optimizer.step()
  File "/home/grant/repos/aud1/yellowfin.py", line 371, in step
    self.after_apply()
  File "/home/grant/repos/aud1/yellowfin.py", line 276, in after_apply
    self.grad_sparsity()
  File "/home/grant/repos/aud1/yellowfin.py", line 219, in grad_sparsity
    grad_non_zero = grad.nonzero()
RuntimeError: an illegal memory access was encountered
```

**Comment by imwebson** [comment]
I have also encountered this problem， and it seems that it will occur sooner or later when i run my program.

**Comment by JianGoForIt** [comment]
Please let me know if the discussion is still active. :)
